services:

  postgres:
    image: postgres:17

    container_name: personal-finance-postgres-dev

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - personal-finance-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev

    container_name: personal-finance-backend-dev

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: dev

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./backend:/app
      - maven_repository:/root/.m2

    ports:
      - "8080:8080"

    stdin_open: true
    tty: true

    networks:
      - personal-finance-network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev

    container_name: personal-finance-frontend-dev

    restart: unless-stopped

    depends_on:
      backend:
        condition: service_started

    environment:
      VITE_API_URL: http://localhost:8080/api

    volumes:
      - ./front:/app
      - /app/node_modules

    ports:
      - "5173:5173"

    stdin_open: true
    tty: true

    networks:
      - personal-finance-network

volumes:
  postgres_data:
  maven_repository:

networks:
  personal-finance-network:
    driver: bridge