import type { Transaction } from "./transaction.types";

export const transactionsMock: Transaction[] = [
    {
        id: "1",
        accountId: "1",
        categoryId: "food",
        title: "Пятёрочка",
        merchant: "Пятёрочка",
        amount: -1320,
        currency: "RUB",
        type: "expense",
        date: "2026-06-27T10:20:00",
    },
    {
        id: "2",
        accountId: "1",
        categoryId: "coffee",
        title: "Starbucks",
        merchant: "Starbucks",
        amount: -540,
        currency: "RUB",
        type: "expense",
        date: "2026-06-27T08:10:00",
    },
    {
        id: "3",
        accountId: "1",
        categoryId: "salary",
        title: "Зарплата",
        amount: 120000,
        currency: "RUB",
        type: "income",
        date: "2026-06-26T18:00:00",
    },
    {
        id: "4",
        accountId: "2",
        categoryId: "transport",
        title: "Яндекс Go",
        merchant: "Yandex Go",
        amount: -730,
        currency: "RUB",
        type: "expense",
        date: "2026-06-26T15:30:00",
    },
    {
        id: "5",
        accountId: "2",
        categoryId: "shopping",
        title: "Ozon",
        merchant: "Ozon",
        amount: -3490,
        currency: "RUB",
        type: "expense",
        date: "2026-06-25T20:10:00",
    },
];